programming_jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs! 🐞",
    "Why do programmers prefer Linux? Because root is always with them! 👨‍💻",
    "Why do Java developers wear glasses? Because they don't see sharp! 👓",
    "Why don't programmers like nature? It has too many bugs. 🐜",
    "Why did the programmer quit his job? He didn't get arrays! 🤔",
    "Why did the computer keep its drink on the windowsill? Because it wanted a byte! 🥤",
    "Why do programmers always mix up Christmas and Halloween? Oct 31 == Dec 25! 🎃🎄",
    "Why do programmers prefer dark chocolate? Because it's byte-sized! 🍫",
    "Why did the programmer go broke? Because he used up all his cache! 💰",
    "Why do programmers prefer iOS development? Because it's the only way to touch a girl! 👩‍💻",
    "Why was the JavaScript developer sad? Because he didn't 'null' how to 'undefined' his feelings! 😢",
    "Why do Python programmers prefer dark alleys? They love snake cases! 🐍",
    "Why do programmers prefer dark chocolate? It's bitter, just like their feelings! 😞",
    "Why don't programmers like to go outside? The sunlight causes too many reflections! ☀️",
    "Why do programmers hate nature? It has too many bugs! 🕷️",
]

programming_quotes = [
    "Hello, World! 🌍",  # Traditional first program
    "The only way to do great work is to love what you do. - Steve Jobs ❤️",
    "First, solve the problem. Then, write the code. - John Johnson 💡",
    "It's not a bug, it's a feature. - Unknown 🐛",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House 😄",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine 🤔",
    "The best error message is the one that never shows up. - Thomas Fuchs 🚫",
    "Programming is the closest thing we have to magic. - Drew Houston ✨",
    "Talk is cheap. Show me the code. - Linus Torvalds 💬",
    "Code before correctness. - Unknown 🚀",
    "Coding is not just code, that is a live thing to serve everyone! - Ming Song 🌐",
    "The most important property of a program is whether it accomplishes the intention of its user. - C.A.R. Hoare 🎯",
    "Code is like a joke: If you have to explain it, it’s not that good. - Cory House 😅",
    "Programming can be fun, so can cryptography; however, they should not be combined. - Kreitzberg and Shneiderman 🔐",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Unknown 🤖",
]
